{
 "title": "Visão Inicial",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Resumo App Local",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volumetria Total",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum by (instance,status_code) (increase(http_requests_total{instance=\"applista:80\"}[5m]))",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Volumetria By Endpoint",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 9, "x": 7, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum by (instance,status_code) (increase(http_requests_total{instance=\"applista:80\"}[5m]))",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Volumetria By Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by (instance,status_code) (increase(http_requests_total{instance=\"applista:80\"}[5m]))",
       "legendFormat": "{{status_code}}"
      }
     ]
    }
   ]
  },
  { "title": "Resumo Docker Local", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Quantidade de Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[1m]))"
    }
   ]
  },
  { "title": "Informações por Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Utilização de Memória",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|applista|prometheus\",image!=\"\"} - container_memory_cache{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|applista|prometheus\",image!=\"\"})\n",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Utilização de CPU %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(container_cpu_user_seconds_total{container_label_com_docker_compose_service=~\"alertmanager|cadvisor|grafana|applista|prometheus\",image!=\"\"}[5m]) * 100)\n",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Tráfego de Entrada por Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tráfego de Saída por Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}