global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:
  - 'alert.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
            - targets: ['cadvisor:8080']
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
            - targets: ['nginx:80']
